%% title: Architecture
%% description: DevSecOps high level architecture
graph LR
  subgraph SecOps Services
    secops-endpoint["VPN endpoint"]
    secops-elk["ELK"]
    secops-nessusmanager["Nessus Manager"]
  end
  subgraph AWS subaccount
    vpn-endpoint["VPN endpoint"]
    iam["AWS IAM"]
    iam-perms["AWS IAM Permissions"]
    iam-roles["AWS IAM Roles"]
    aws-console["AWS Console"]
    s3["AWS S3"]
    kinesis["AWS Kinesis"]
    route53["AWS Route 53"]
    cloudwatch["AWS CloudWatch Metrics"]
    cloudwatch-logs["AWS CloudWatch Logs"]
    cloudtrail["AWS CloudTrail"]
    subgraph Application VPC
      subgraph Availability Zones us-east-1a/b
        subgraph Public Subnet
          app-nat["NAT Gateway"]
        end
        subgraph Private Subnet
          app-app["Application"]
        end
        subgraph Private Subnet - Database
          app-rds{"AWS RDS instances"}
        end
      end
      vpc-router-apps["VPC Router"]
    end
    vpc-peering["VPC Peering Connection"]
    subgraph Management VPC
      vpc-router-mgmt["VPC Router"]
      subgraph Availability Zones us-east-1a/b
        subgraph Public Subnet
          mgmt-nat["NAT Gateway"]
        end
        subgraph Private Subnet - Database
          mgmt-rds{"AWS RDS instances"}
        end
        subgraph Private Subnet
          mgmt-jenkins["Jenkins"]
          mgmt-elk["ELK"]
        end
      end
    end
  end

  secops-endpoint---vpn-endpoint

  cloudwatch-logs-- Encrypted log data only --- kinesis

  aws-console-."Authentication/Authorization".->iam
  iam-.->iam-perms
  iam-perms-.->iam-roles

  vpc-router-mgmt-->vpc-peering
  vpc-router-apps-->vpc-peering

  app-nat---app-app
  app-nat---app-rds

  mgmt-nat---mgmt-rds
  mgmt-nat---mgmt-jenkins


