%% title: Architecture Option B
%% description: DevSecOps high level architecture Option B
graph LR
  gsa-users(("GSA Network Users"))
  subgraph SecOps Maintained VPC
    vpc-router-secops["VPC Router"]
    secops-log["SecOps logging stack"]
    secops-nessusmanager["Nessus Manager"]
  end
  subgraph IDI Maintained VPC
    vpc-router-mgmt["VPC Router"]
    mgmt-jenkins["Jenkins"]
    mgmt-log["Logging stack"]
    mgmt-monitoring["Metrics/Monitoring"]
  end
  subgraph AWS subaccount
    iam["AWS IAM"]
    iam-perms["AWS IAM Permissions"]
    iam-roles["AWS IAM Roles"]
    aws-console["AWS Console"]
    s3["AWS S3"]
    kinesis["AWS Kinesis"]
    elasticsearch["AWS Elasticsearch Service"]
    route53["AWS Route 53"]
    cloudwatch["AWS CloudWatch Metrics"]
    cloudwatch-logs["AWS CloudWatch Logs"]
    cloudtrail["AWS CloudTrail"]
    vpc-peering-secops["VPC Peering Connection - SecOps VPC"]
    subgraph Application VPC
      subgraph Availability Zones us-east-1a/b
        subgraph Public Subnet
          app-nat["NAT Gateway"]
          app-elb["Load Balancer"]
        end
        subgraph Private Subnet
          app-app["Application"]
        end
        subgraph Private Subnet - Database
          app-rds{"AWS RDS instances"}
        end
      end
      vpc-router-apps["VPC Router"]
    end
    vpc-peering-pipeline["VPC Peering Connection - IDI VPC"]
  end

  cloudwatch-logs-- Encrypted log data only --- kinesis

  aws-console-."Authentication/Authorization".->iam
  iam-.->iam-perms
  iam-perms-.->iam-roles

  vpc-peering-pipeline---vpc-router-mgmt
  vpc-peering-secops---vpc-router-secops

  vpc-router-secops--SecurityGroup---secops-log
  vpc-router-secops--SecurityGroup---secops-nessusmanager

  vpc-router-mgmt--SecurityGroup---mgmt-jenkins
  vpc-router-mgmt--SecurityGroup---mgmt-log
  vpc-router-mgmt--SecurityGroup---mgmt-monitoring

  vpc-router-apps---vpc-peering-pipeline
  vpc-router-apps---vpc-peering-secops
  vpc-router-apps---app-nat

  app-elb-->app-nat
  app-nat--SecurityGroup---app-app
  app-nat--SecurityGroup---app-rds

  gsa-users--SecurityGroup-->app-elb


