%% title: Architecture Option C
%% description: DevSecOps high level architecture Option C
graph LR
  gsa-users(("GSA Network Users"))
  subgraph SecOps Maintained VPC
    vpc-router-secops["VPC Router"]
    secops-log["SecOps logging stack"]
    secops-nessusmanager["Nessus Manager"]
  end
  subgraph IDI Maintained VPC
    subgraph Availability Zones us-east-1a/b
      vpc-router-idi-mgmt["VPC Router"]
      subgraph Public Subnet
        idi-mgmt-nat["NAT Gateway"]
        idi-mgmt-jumpbox["Jumpbox"]
      end
      subgraph Private Subnet - Database
        idi-mgmt-rds{"AWS RDS instances"}
      end
      subgraph Private Subnet
        idi-mgmt-jenkins["Jenkins"]
        idi-mgmt-artifact-repository["Artifact Repository"]
        idi-mgmt-log["Logging stack"]
        idi-mgmt-monitoring["Metrics/Monitoring"]
      end
    end
  end
  subgraph AWS subaccount
    iam["AWS IAM"]
    iam-perms["AWS IAM Permissions"]
    iam-roles["AWS IAM Roles"]
    aws-console["AWS Console"]
    aws-cli["AWS CLI"]
    s3["AWS S3"]
    kinesis["AWS Kinesis"]
    elasticsearch["AWS Elasticsearch Service"]
    route53["AWS Route 53"]
    aws-sqs["AWS SQS"]
    cloudwatch["AWS CloudWatch Metrics"]
    cloudwatch-logs["AWS CloudWatch Logs"]
    cloudtrail["AWS CloudTrail"]
    vpc-peering-secops["VPC Peering Connection - SecOps VPC"]
    vpc-peering-cust-mgmt["VPC Peering Connection - Customer Management VPC"]
    vpc-peering-idi-pipeline["VPC Peering Connection - IDI VPC"]
    subgraph Application VPC
      subgraph Availability Zones us-east-1a/b
      vpc-router-cust-apps["VPC Router"]
        subgraph Public Subnet
          app-nat["NAT Gateway"]
          app-elb["Load Balancer"]
        end
        subgraph Private Subnet
          app-app["Application"]
        end
        subgraph Private Subnet - Database
          app-rds{"AWS RDS instances"}
        end
      end
    end
    subgraph Customer-Management VPC
      subgraph Availability Zones us-east-1a/b
      vpc-router-cust-mgmt["VPC Router"]
        subgraph Public Subnet
          cust-mgmt-nat["NAT Gateway"]
          cust-mgmt-jumpbox["Jumpbox"]
        end
        subgraph Private Subnet - Database
          cust-mgmt-rds{"AWS RDS instances"}
        end
        subgraph Private Subnet
          cust-mgmt-jenkins["Jenkins"]
          cust-mgmt-artifact-repository["Artifact Repository"]
          cust-mgmt-log["Logging stack"]
          cust-mgmt-monitoring["Metrics/Monitoring"]
        end
      end
    end
  end

  cloudwatch-logs-- Encrypted log data only --- kinesis

  aws-console-."Authentication/Authorization".->iam
  aws-cli-."Authentication/Authorization".->iam
  iam-.->iam-perms
  iam-perms-.->iam-roles

  vpc-peering-idi-pipeline---vpc-router-idi-mgmt
  vpc-peering-secops---vpc-router-secops
  vpc-peering-cust-mgmt---vpc-router-cust-mgmt

  vpc-router-secops--SecurityGroup---secops-log
  vpc-router-secops--SecurityGroup---secops-nessusmanager

  vpc-router-idi-mgmt---idi-mgmt-nat

  idi-mgmt-nat--SecurityGroup---idi-mgmt-rds
  idi-mgmt-nat--SecurityGroup---idi-mgmt-jenkins
  idi-mgmt-nat--SecurityGroup---idi-mgmt-artifact-repository
  idi-mgmt-nat--SecurityGroup---idi-mgmt-log
  idi-mgmt-nat--SecurityGroup---idi-mgmt-monitoring

  vpc-router-cust-apps---vpc-peering-idi-pipeline
  vpc-router-cust-apps---vpc-peering-secops
  vpc-router-cust-apps---vpc-peering-cust-mgmt
  vpc-router-cust-apps---app-nat
  
  vpc-router-cust-mgmt---cust-mgmt-nat

  cust-mgmt-nat--SecurityGroup---cust-mgmt-rds
  cust-mgmt-nat--SecurityGroup---cust-mgmt-jenkins
  cust-mgmt-nat--SecurityGroup---cust-mgmt-artifact-repository
  cust-mgmt-nat--SecurityGroup---cust-mgmt-log
  cust-mgmt-nat--SecurityGroup---cust-mgmt-monitoring

  app-elb-->app-nat
  app-nat--SecurityGroup---app-app
  app-nat--SecurityGroup---app-rds

  gsa-users--SecurityGroup-->app-elb


