%% title: Architecture Option A
%% description: DevSecOps high level architecture Option A
graph LR
  gsa-users(("GSA Network Users"))
  subgraph SecOps Maintained Services VPC
    vpc-router-secops["VPC Router"]
    secops-log["SecOps logging stack"]
    secops-nessusmanager["Nessus Manager"]
  end
  subgraph AWS subaccount
    iam["AWS IAM"]
    iam-perms["AWS IAM Permissions"]
    iam-roles["AWS IAM Roles"]
    aws-console["AWS Console"]
    aws-cli["AWS CLI"]
    s3["AWS S3"]
    kinesis["AWS Kinesis"]
    route53["AWS Route 53"]
    aws-sqs["AWS SQS"]
    cloudwatch["AWS CloudWatch Metrics"]
    cloudwatch-logs["AWS CloudWatch Logs"]
    cloudtrail["AWS CloudTrail"]
    vpc-peering-secops["VPC Peering Connection - SecOps"]
    subgraph Application VPC
      subgraph Availability Zones us-east-1a/b
        subgraph Public Subnet
          app-nat["NAT Gateway"]
          app-elb["Load Balancer"]
        end
        subgraph Private Subnet
          app-app["Application"]
        end
        subgraph Private Subnet - Database
          app-rds{"AWS RDS instances"}
        end
      end
      vpc-router-apps["VPC Router"]
    end
    vpc-peering-pipeline["VPC Peering Connection - Internal"]
    subgraph Management VPC
      vpc-router-mgmt["VPC Router"]
      subgraph Availability Zones us-east-1a/b
        subgraph Public Subnet
          mgmt-nat["NAT Gateway"]
          mgmt-jumpbox["Jumpbox"]
        end
        subgraph Private Subnet - Database
          mgmt-rds{"AWS RDS instances"}
        end
        subgraph Private Subnet
          mgmt-jenkins["Jenkins"]
          mgmt-artifact-repository["Artifact Repository"]
          mgmt-log["Logging stack"]
          mgmt-monitoring["Metrics/Monitoring"]
        end
      end
    end
  end

  cloudwatch-logs-- Encrypted log data only --- kinesis

  aws-console-."Authentication/Authorization".->iam
  aws-cli-."Authentication/Authorization".->iam
  iam-.->iam-perms
  iam-perms-.->iam-roles

  vpc-router-secops---vpc-peering-secops
  vpc-router-mgmt---vpc-peering-pipeline
  vpc-router-mgmt---vpc-peering-secops
  vpc-router-mgmt---mgmt-nat
  vpc-router-apps---vpc-peering-pipeline
  vpc-router-apps---vpc-peering-secops
  vpc-router-apps---app-nat

  app-elb-->app-nat
  app-nat--SecurityGroup---app-app
  app-nat--SecurityGroup---app-rds

  mgmt-nat--SecurityGroup---mgmt-rds
  mgmt-nat--SecurityGroup---mgmt-jenkins
  mgmt-nat--SecurityGroup---mgmt-artifact-repository
  mgmt-nat--SecurityGroup---mgmt-log
  mgmt-nat--SecurityGroup---mgmt-monitoring

  gsa-users--SecurityGroup-->app-elb


