%% title: Architecture-Prod
%% description: DevSecOps Prod - 1 AWS account == 1 VPC
graph LR
  gsa-users(("GSA Network Users"))
  public-internet(("Public Internet"))
  github["GitHub"]
  netops-aws-vpc["NetOps VPC"]
  secops-aws-vpc["SecOps VPC"]
  vpn-tunnel1["VPN Tunnel 1"]
  vpn-tunnel2["VPN Tunnel 2"]
  subgraph AWS subaccount
    iam["AWS IAM"]
    iam-perms["AWS IAM Permissions"]
    iam-roles["AWS IAM Roles"]
    aws-console["AWS Console"]
    aws-cli["AWS CLI"]
    s3["AWS S3"]
    glacier["AWS Glacier"]
    kinesis["AWS Kinesis"]
    route53["AWS Route 53"]
    aws-sqs["AWS SQS"]
    aws-sns["AWS SNS"]
    aws-lambda["AWS Lambda"]
    mgmt-lambda-custodian["Cloud Custodian"]
    cloudwatch["AWS CloudWatch Metrics"]
    cloudwatch-logs["AWS CloudWatch Logs"]
    cloudtrail["AWS CloudTrail"]
    subgraph Customer VPC-Dev, Test or Prod
      subgraph Availability Zone-Primary
          vpc-vgw1["VPC VGW1"]
          vpc-vgw2["VPC VGW2"]
        subgraph App Public Subnet
          app-nat["NAT Gateway"]
          app-alb["App Load Balancer"]
        end
        subgraph App Private Subnet
          app-app["Application"]
        end
        subgraph App Private RDS Subnets
          app-rds{"AWS RDS instances"}
        end
      end
      subgraph Availability Zone-Failover
          vpc-vgw1-standby["VPC VGW1 Standby"]
          vpc-vgw2=standby["VPC VGW2 Standby"]
        subgraph App Public Subnet
          app-nat-standby["NAT Gateway-Standby"]
          app-alb-standby["App Load Balancer-Standby"]
        end
        subgraph App Private Subnet
          app-app-standby["Application-Standby"]
        end
        subgraph App Private RDS Subnets
          app-rds-standby{"AWS RDS-Read Replicas"}
        end
      end
    end
  end

  cloudwatch-logs-- Encrypted log data only --- kinesis

  aws-console-."Authentication/Authorization".->iam
  aws-cli-."Authentication/Authorization".->iam
  iam-.->iam-perms
  iam-perms-.->iam-roles
  mgmt-lambda-custodian-.->aws-lambda
  s3-.->glacier

  github---public-internet
  gsa-users---netops-aws-vpc
  public-internet---netops-aws-vpc
  secops-aws-vpc---netops-aws-vpc
  netops-aws-vpc---vpn-tunnel1
  netops-aws-vpc---vpn-tunnel2

  vpn-tunnel1---vpc-vgw1
  vpn-tunnel2---vpc-vgw2

  vpc-vgw1--SecurityGroup---app-alb
  vpc-vgw1---app-nat

  vpc-vgw2--SecurityGroup---app-alb
  vpc-vgw2---app-nat

  app-alb--SecurityGroup-->app-app
  app-nat--SecurityGroup---app-app
  app-nat--SecurityGroup---app-rds

  app-rds---app-rds-standby